### PR TITLE
pg_loggrep - no normal output for aggregates

### PR DESCRIPTION
**Pull request by kmoppel**

### CODE REVIEW

**Comment by a1exsh** [comment]
Maybe it should be an option to still display normal output and then the aggregates?

**Comment by kmoppel** [comment]
@a1exsh I think it's just a bugfix :) It was meant to be like that and for most aggregates it also actually worked but now it's just enforced one level higher.

**Comment by a1exsh** [comment]
:+1:

**Comment by LappleApple** [comment]
This PR's still open, needs a Zappr check. Plans to merge it?

**Comment by slitsche** [comment]
👍

**Pull request merged**
